version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies for testing...
      - npm ci
      - echo Installing testing tools...
      - npm install -g jest@latest
      
  pre_build:
    commands:
      - echo Pre-build testing phase started on `date`
      - echo Setting up test environment...
      - cp .env.template .env.test || echo "No template found, using defaults"
      - echo Validating test configuration...
      
  build:
    commands:
      - echo Testing phase started on `date`
      - echo Running unit tests with coverage...
      - npm run test:coverage
      - echo Running integration tests...
      - npm run test:integration
      - echo Running end-to-end tests...
      - npm run test:e2e || echo "E2E tests not configured, skipping..."
      - echo Running security tests...
      - npm run test:security || echo "Security tests not configured, skipping..."
      
  post_build:
    commands:
      - echo Post-build testing phase completed on `date`
      - echo Generating test reports...
      - echo Test phase completed successfully

artifacts:
  files:
    - coverage/**/*
    - test-results/**/*
    - reports/**/*
  name: test-results-$(date +%Y-%m-%d-%H-%M-%S)

reports:
  jest-reports:
    files:
      - 'coverage/lcov.info'
      - 'test-results/junit.xml'
    base-directory: '.'
    file-format: 'JUNITXML'